name: 'the_tuva_project'
version: '0.3.13'
config-version: 2
require-dbt-version: ">=1.3.0"


profile: default

vars:

    ## CCSR data mart vars
    # These vars enable the wide tables - disabling will exclude wide tables from dbt runs
    wide_condition_enabled: True
    wide_procedure_enabled: True

    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"


    ## CMS HCC data mart vars
    # The payment_year variable has a default of the current year
    cms_hcc_payment_year: 2023

    # DO NOT CHANGE - Future logic to be added for selecting different HCC model versions
    cms_hcc_model_version: CMS-HCC-V24


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  the_tuva_project:
    terminology:
      terminology__admit_source:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','admit_source.csv') }}"
      terminology__admit_type:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','admit_type.csv') }}"
      terminology__ansi_fips_state:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','ansi_fips_state.csv') }}"
      terminology__apr_drg:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','apr_drg.csv') }}"
      terminology__bill_type:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','bill_type.csv') }}"
      terminology__calendar:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','calendar.csv') }}"
      terminology__claim_type:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','claim_type.csv') }}"
      terminology__code_type:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','code_type.csv') }}"
      terminology__discharge_disposition:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','discharge_disposition.csv') }}"
      terminology__encounter_type:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','encounter_type.csv') }}"
      terminology__ethnicity:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','ethnicity.csv') }}"
      terminology__fips_county:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','fips_county.csv') }}"
      terminology__gender:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','gender.csv') }}"
      terminology__hcpcs_level_2:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','hcpcs_level_2.csv') }}"
      terminology__icd_10_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','icd_10_cm.csv') }}"
      terminology__icd_10_pcs:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','icd_10_pcs.csv') }}"
      terminology__icd_9_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','icd_9_cm.csv') }}"
      terminology__mdc:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','mdc.csv') }}"
      terminology__medicare_dual_eligibility:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','medicare_dual_eligibility.csv') }}"
      terminology__medicare_status:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','medicare_status.csv') }}"
      terminology__ms_drg:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','ms_drg.csv') }}"
      terminology__other_provider_taxonomy:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data/version_1','other_provider_taxonomy.csv') }}"
      terminology__payer_type:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','payer_type.csv') }}"
      terminology__place_of_service:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','place_of_service.csv') }}"
      terminology__present_on_admission:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','present_on_admission.csv') }}"
      terminology__provider:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data/version_1','provider.csv') }}"
      terminology__race:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','race.csv') }}"
      terminology__revenue_center:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','revenue_center.csv') }}"
      terminology__ssa_fips_state:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology/version_1','ssa_fips_state.csv') }}"


  
    value_sets:
      ccsr:
        ccsr__dxccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','dxccsr_v2023_1_cleaned_map.csv') }}"
        ccsr__prccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','prccsr_v2023_1_cleaned_map.csv') }}"

      chronic_conditions:
        chronic_conditions__cms_chronic_conditions_hierarchy:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','cms_chronic_conditions_hierarchy.csv') }}"
        chronic_conditions__tuva_chronic_conditions_hierarchy:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','tuva_chronic_conditions_hierarchy.csv') }}"

      cms_hcc:
        cms_hcc__adjustment_rates:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','adjustment_rates.csv') }}"
        cms_hcc__cpt_hcpcs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','cpt_hcpcs.csv') }}"
        cms_hcc__demographic_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','demographic_factors.csv') }}"
        cms_hcc__disabled_interaction_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','disabled_interaction_factors.csv') }}"
        cms_hcc__disease_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','disease_factors.csv') }}"
        cms_hcc__disease_hierarchy:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','disease_hierarchy.csv') }}"
        cms_hcc__disease_interaction_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','disease_interaction_factors.csv') }}"
        cms_hcc__enrollment_interaction_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','enrollment_interaction_factors.csv') }}"
        cms_hcc__icd_10_cm_mappings:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','icd_10_cm_mappings.csv') }}"
        cms_hcc__payment_hcc_count_factors:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','payment_hcc_count_factors.csv') }}"

      data_profiling:
        data_profiling__test_catalog:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','test_catalog.csv') }}"

      readmissions:
        readmissions__icd_10_pcs_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','icd_10_pcs_to_ccs.csv') }}"
        readmissions__icd_10_cm_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','icd_10_cm_to_ccs.csv') }}"
      
      service_category:
        service_category__service_categories:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets/version_1','service_categories.csv') }}"
